In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        selectk_features = fit1.transform(indep_X)
        return selectk_features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
   
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])     
    dataframe['Logistic']['ChiSquare']=acclog      
    dataframe['SVMl']['ChiSquare']=accsvml
    dataframe['SVMnl']['ChiSquare']=accsvmnl
    dataframe['KNN']['ChiSquare']=accknn
    dataframe['Navie']['ChiSquare']=accnav
    dataframe['Decision']['ChiSquare']=accdes
    dataframe['Random']['ChiSquare']=accrf
    return dataframe

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df2 = pd.get_dummies(df2, drop_first=True)

indep_X=df2.drop('classification_yes',axis=1)
dep_Y=df2['classification_yes']

In [4]:
df2

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [5]:
indep_X

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...        True      False        False   
1    137.528754  4.627244  10.700000  ...        True       True        False   
2    138.000000  4.400000  12.000000  ...        True       True        False   
3    138.000000  3.200000   8.100000  ...        True       True        False   
4    137.528754  4.627244  11.800000  ...        True       True        False   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...        True       True        False   
395  137.528754  4.627244   8.700000  ...        True       True        False   
396  134.000000  2.700000   9.100000  ...        True       True        False   
397  142.000000  5.500000   8.500000  ...        True       True        False   
398  140.000000  5.000000  16.300000  ...        True       True        False   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0         False    False   False    False       True    True    False  
1         False    False   False    False       True   False    False  
2         False    False   False    False       True   False    False  
3         False    False   False    False       True   False     True  
4         False    False   False    False       True   False    False  
..          ...      ...     ...      ...        ...     ...      ...  
394       False    False   False    False       True   False    False  
395       False     True    True    False       True   False     True  
396       False     True    True    False      False   False    False  
397       False     True    True    False       True   False     True  
398       False    False   False    False       True   False    False  

[399 rows x 27 columns]

In [6]:
dep_Y

0       True
1       True
2       True
3       True
4       True
       ...  
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [7]:
kbest=selectkbest(indep_X,dep_Y,5)       

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [8]:
df= pd.DataFrame(kbest)
df
# Here it has found the best 5 input features combinations

0           1         2          3             4
0    148.112676   57.482105  3.077356  38.868902   8408.191126
1    148.112676   22.000000  0.700000  34.000000  12300.000000
2     99.000000   23.000000  0.600000  34.000000   8408.191126
3    148.112676   16.000000  0.700000  38.868902   8408.191126
4    148.112676   25.000000  0.600000  36.000000  12400.000000
..          ...         ...       ...        ...           ...
394  219.000000   36.000000  1.300000  37.000000   9800.000000
395  220.000000   68.000000  2.800000  27.000000   8408.191126
396  110.000000  115.000000  6.000000  26.000000   9200.000000
397  207.000000   80.000000  6.800000  38.868902   8408.191126
398  100.000000   49.000000  1.000000  53.000000   8500.000000

[399 rows x 5 columns]

In [9]:
#passing the kbest Inputs and performing input output split and then standardising the input features
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)   

In [10]:
y_train

250     True
63      True
312    False
159     True
283    False
       ...  
323     True
192     True
117     True
47     False
172    False
Name: classification_yes, Length: 299, dtype: bool

In [11]:
y_test

132    False
309     True
334    False
196     True
246     True
       ...  
146     True
135     True
389     True
264     True
363     True
Name: classification_yes, Length: 100, dtype: bool

In [12]:
X_train

array([[-0.53161371,  0.66735057,  0.11812851,  0.25241909,  0.06186409],
       [-0.42338918, -0.6076989 , -0.17636765, -0.00680427,  0.06186409],
       [-0.73453472, -0.77645545, -0.4362172 ,  0.25241909, -1.26712075],
       ...,
       [-0.55866985, -0.85145836, -0.38424729, -0.23413463,  0.82799677],
       [-0.80217505, -0.34518871, -0.47086381,  1.59044182,  0.82799677],
       [-0.26105237, -0.66395108, -0.34960069,  0.13078066, -0.06991074]])

In [13]:
X_test

array([[-6.53366316e-01, -2.51435077e-01, -4.70863811e-01,
         4.95695949e-01, -1.09609075e+00],
       [ 6.36212327e-02,  2.92336021e-01,  1.41886893e-02,
        -6.80427059e-03,  6.18640859e-02],
       [-8.83343454e-01, -3.45188714e-01, -3.49600686e-01,
         1.34716496e+00,  4.43179269e-01],
       [ 2.01166287e+00, -1.38930712e-01, -7.24278287e-02,
        -5.99049917e-01,  2.28175179e+00],
       [-5.85725981e-01, -1.38930712e-01, -1.59044347e-01,
        -7.20688347e-01,  9.56269275e-01],
       [ 6.36212327e-02, -7.20203265e-01, -4.01570597e-01,
        -6.80427059e-03,  6.18640859e-02],
       [-2.61052374e-01,  1.82989568e+00,  1.48666949e+00,
        -1.81543421e+00,  5.71451771e-01],
       [ 2.86393109e+00, -7.76455447e-01, -4.36217204e-01,
         6.17334379e-01,  1.56042646e-02],
       [-1.52827839e-01, -8.13956902e-01, -4.70863811e-01,
         6.17334379e-01, -1.55425737e-01],
       [-1.05920832e+00, -2.70185804e-01, -3.49600686e-01,
         1.34716496e+00

In [14]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [15]:
dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])      
dataframe['Logistic']['ChiSquare']=acclog       
dataframe['SVMl']['ChiSquare']=accsvml
dataframe['SVMnl']['ChiSquare']=accsvmnl
dataframe['KNN']['ChiSquare']=accknn
dataframe['Navie']['ChiSquare']=accnav
dataframe['Decision']['ChiSquare']=accdes
dataframe['Random']['ChiSquare']=accrf

In [16]:
dataframe

Logistic    SVMl   SVMnl     KNN   Navie Decision  Random
ChiSquare   [0.94]  [0.94]  [0.95]  [0.89]  [0.83]   [0.96]  [0.95]

In [17]:
df=pd.DataFrame(columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])   
df.loc[0, "Logistic"] = acclog

In [18]:
df

Logistic SVMl SVMnl  KNN Navie Decision Random
0   [0.94]  NaN   NaN  NaN   NaN      NaN    NaN

In [19]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [20]:
result

Logistic    SVMl   SVMnl     KNN   Navie Decision  Random
ChiSquare   [0.94]  [0.94]  [0.95]  [0.89]  [0.83]   [0.96]  [0.95]

In [21]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [22]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [23]:
result

Logistic  SVMl SVMnl   KNN Navie Decision Random
ChiSquare     0.94  0.94  0.95  0.89  0.83     0.96   0.95

In [24]:
svm_linear(X_train,y_train,X_test)

(SVC(kernel='linear', random_state=0),
 0.94,
 '              precision    recall  f1-score   support\n\n       False       0.89      0.94      0.92        36\n        True       0.97      0.94      0.95        64\n\n    accuracy                           0.94       100\n   macro avg       0.93      0.94      0.94       100\nweighted avg       0.94      0.94      0.94       100\n',
 array([[-6.53366316e-01, -2.51435077e-01, -4.70863811e-01,
          4.95695949e-01, -1.09609075e+00],
        [ 6.36212327e-02,  2.92336021e-01,  1.41886893e-02,
         -6.80427059e-03,  6.18640859e-02],
        [-8.83343454e-01, -3.45188714e-01, -3.49600686e-01,
          1.34716496e+00,  4.43179269e-01],
        [ 2.01166287e+00, -1.38930712e-01, -7.24278287e-02,
         -5.99049917e-01,  2.28175179e+00],
        [-5.85725981e-01, -1.38930712e-01, -1.59044347e-01,
         -7.20688347e-01,  9.56269275e-01],
        [ 6.36212327e-02, -7.20203265e-01, -4.01570597e-01,
         -6.80427059e-03,  6.186408

In [25]:
#Here in the below code y_test IS NOT PASSED AS AN ARGUMENT BUT STILL THE CODE WORKS BECAUSE OF GLOBAL OR ENCLOSING...
...#POLICY BUT THE BEST PRACTISE WOULD BE TO GIVE THE VARIABLE y_test  AS AN ARGUMENT TO THE FUNCTION

Ellipsis

In [26]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm


In [27]:
cm_prediction(classifier,X_test)

(RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0),
 0.95,
 '              precision    recall  f1-score   support\n\n       False       0.90      0.97      0.93        36\n        True       0.98      0.94      0.96        64\n\n    accuracy                           0.95       100\n   macro avg       0.94      0.95      0.95       100\nweighted avg       0.95      0.95      0.95       100\n',
 array([[-6.53366316e-01, -2.51435077e-01, -4.70863811e-01,
          4.95695949e-01, -1.09609075e+00],
        [ 6.36212327e-02,  2.92336021e-01,  1.41886893e-02,
         -6.80427059e-03,  6.18640859e-02],
        [-8.83343454e-01, -3.45188714e-01, -3.49600686e-01,
          1.34716496e+00,  4.43179269e-01],
        [ 2.01166287e+00, -1.38930712e-01, -7.24278287e-02,
         -5.99049917e-01,  2.28175179e+00],
        [-5.85725981e-01, -1.38930712e-01, -1.59044347e-01,
         -7.20688347e-01,  9.56269275e-01],
        [ 6.36212327e-02, -7.20203265e-01, -4.01570597e