In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        # summarize scores       
        selectk_features = fit1.transform(indep_X)
        return selectk_features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2
 
def Linear(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2   
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training setC
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def random(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2 
    
    
def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Linear','SVMl','SVMnl','Decision','Random'
                                                                                     ])

    for number,idex in enumerate(dataframe.index):
        
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [3]:
dataset1=pd.read_csv("prep.csv")

df2=dataset1

df2 = pd.get_dummies(df2,dtype=int, drop_first=True)

indep_X=df2.drop('classification_yes',axis=1)
dep_Y=df2['classification_yes']

In [4]:
df2

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [5]:
indep_X

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [6]:
kbest=selectkbest(indep_X,dep_Y,5)

In [7]:
df=pd.DataFrame(kbest)
df

0           1         2          3             4
0    148.112676   57.482105  3.077356  38.868902   8408.191126
1    148.112676   22.000000  0.700000  34.000000  12300.000000
2     99.000000   23.000000  0.600000  34.000000   8408.191126
3    148.112676   16.000000  0.700000  38.868902   8408.191126
4    148.112676   25.000000  0.600000  36.000000  12400.000000
..          ...         ...       ...        ...           ...
394  219.000000   36.000000  1.300000  37.000000   9800.000000
395  220.000000   68.000000  2.800000  27.000000   8408.191126
396  110.000000  115.000000  6.000000  26.000000   9200.000000
397  207.000000   80.000000  6.800000  38.868902   8408.191126
398  100.000000   49.000000  1.000000  53.000000   8500.000000

[399 rows x 5 columns]

In [8]:
df.index

RangeIndex(start=0, stop=399, step=1)

In [9]:
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [10]:
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)
X_train

array([[-0.53161371,  0.66735057,  0.11812851,  0.25241909,  0.06186409],
       [-0.42338918, -0.6076989 , -0.17636765, -0.00680427,  0.06186409],
       [-0.73453472, -0.77645545, -0.4362172 ,  0.25241909, -1.26712075],
       ...,
       [-0.55866985, -0.85145836, -0.38424729, -0.23413463,  0.82799677],
       [-0.80217505, -0.34518871, -0.47086381,  1.59044182,  0.82799677],
       [-0.26105237, -0.66395108, -0.34960069,  0.13078066, -0.06991074]])

In [11]:
X_test

array([[-6.53366316e-01, -2.51435077e-01, -4.70863811e-01,
         4.95695949e-01, -1.09609075e+00],
       [ 6.36212327e-02,  2.92336021e-01,  1.41886893e-02,
        -6.80427059e-03,  6.18640859e-02],
       [-8.83343454e-01, -3.45188714e-01, -3.49600686e-01,
         1.34716496e+00,  4.43179269e-01],
       [ 2.01166287e+00, -1.38930712e-01, -7.24278287e-02,
        -5.99049917e-01,  2.28175179e+00],
       [-5.85725981e-01, -1.38930712e-01, -1.59044347e-01,
        -7.20688347e-01,  9.56269275e-01],
       [ 6.36212327e-02, -7.20203265e-01, -4.01570597e-01,
        -6.80427059e-03,  6.18640859e-02],
       [-2.61052374e-01,  1.82989568e+00,  1.48666949e+00,
        -1.81543421e+00,  5.71451771e-01],
       [ 2.86393109e+00, -7.76455447e-01, -4.36217204e-01,
         6.17334379e-01,  1.56042646e-02],
       [-1.52827839e-01, -8.13956902e-01, -4.70863811e-01,
         6.17334379e-01, -1.55425737e-01],
       [-1.05920832e+00, -2.70185804e-01, -3.49600686e-01,
         1.34716496e+00

In [12]:
# Fitting K-NN to the Training set
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [13]:
y_pred= regressor.predict(X_test)
y_pred

array([0. , 1. , 0. , 1. , 1. , 1. , 1. , 1. , 0.1, 0. , 1. , 1. , 0. ,
       1. , 0. , 0.4, 1. , 0. , 1. , 1. , 0. , 1. , 1. , 0. , 1. , 0. ,
       0. , 0. , 1. , 0.6, 1. , 1. , 0.3, 0.2, 0. , 0. , 0.6, 0. , 1. ,
       0. , 0. , 1. , 0.8, 0.8, 1. , 0.6, 1. , 0.4, 1. , 1. , 1. , 1. ,
       1. , 0. , 1. , 1. , 0. , 1. , 0. , 0. , 0. , 0.5, 0.6, 1. , 0.9,
       1. , 1. , 0.4, 0. , 1. , 0. , 1. , 0. , 0. , 0. , 0.5, 1. , 1. ,
       0.4, 0. , 1. , 1. , 0. , 0. , 1. , 1. , 0. , 1. , 1. , 1. , 1. ,
       1. , 0. , 0.8, 1. , 0.7, 0.9, 1. , 0.9, 1. ])

In [14]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_pred)
r2

0.8368055555555556

In [15]:
def RF(X_train, y_train,X_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
    regressor.fit(X_train, y_train)
    ypred= regressor.predict(X_test)
    return regressor,ypred

In [16]:
regressor,ypred=RF(X_train, y_train,X_test)

In [17]:
def rscore(y_test,ypred):
    from sklearn.metrics import r2_score
    r2=r2_score(y_test,ypred)
    return r2

In [18]:
r2=rscore(y_test,ypred)
r2

0.8368055555555556

In [19]:
# hERE IN THE BELOW CODE THE INTERNAL FUNCTION r2_prediction CAN ACCESS THE EXTERNAL VARIABLE y_test IF IT IS PASSED AS AN ARGUMENT

In [20]:
def random(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2 

In [21]:
random(X_train,y_train,X_test)

0.8368055555555556

In [22]:
r2_lin=Linear(X_train,y_train,X_test)
acclin.append(r2_lin)

r2_sl=svm_linear(X_train,y_train,X_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test)
accdes.append(r2_d)

r2_r=random(X_train,y_train,X_test)
accrf.append(r2_r)

In [24]:
result5=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)
result5

C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:86: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Linear'][idex]=acclin[number]
C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:87: FutureWarning: Chain

Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806

In [33]:
kbest=selectkbest(indep_X,dep_Y,4)
kbest


array([[1.48112676e+02, 5.74821053e+01, 3.07735602e+00, 8.40819113e+03],
       [1.48112676e+02, 2.20000000e+01, 7.00000000e-01, 1.23000000e+04],
       [9.90000000e+01, 2.30000000e+01, 6.00000000e-01, 8.40819113e+03],
       ...,
       [1.10000000e+02, 1.15000000e+02, 6.00000000e+00, 9.20000000e+03],
       [2.07000000e+02, 8.00000000e+01, 6.80000000e+00, 8.40819113e+03],
       [1.00000000e+02, 4.90000000e+01, 1.00000000e+00, 8.50000000e+03]])

In [34]:
split_scalar(kbest,dep_Y)

(array([[-0.53161371,  0.66735057,  0.11812851,  0.06186409],
        [-0.42338918, -0.6076989 , -0.17636765,  0.06186409],
        [-0.73453472, -0.77645545, -0.4362172 , -1.26712075],
        ...,
        [-0.55866985, -0.85145836, -0.38424729,  0.82799677],
        [-0.80217505, -0.34518871, -0.47086381,  0.82799677],
        [-0.26105237, -0.66395108, -0.34960069, -0.06991074]]),
 array([[-6.53366316e-01, -2.51435077e-01, -4.70863811e-01,
         -1.09609075e+00],
        [ 6.36212327e-02,  2.92336021e-01,  1.41886893e-02,
          6.18640859e-02],
        [-8.83343454e-01, -3.45188714e-01, -3.49600686e-01,
          4.43179269e-01],
        [ 2.01166287e+00, -1.38930712e-01, -7.24278287e-02,
          2.28175179e+00],
        [-5.85725981e-01, -1.38930712e-01, -1.59044347e-01,
          9.56269275e-01],
        [ 6.36212327e-02, -7.20203265e-01, -4.01570597e-01,
          6.18640859e-02],
        [-2.61052374e-01,  1.82989568e+00,  1.48666949e+00,
          5.71451771e-01],
    

In [35]:
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

r2_lin=Linear(X_train,y_train,X_test)
acclin.append(r2_lin)

r2_sl=svm_linear(X_train,y_train,X_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test)
accdes.append(r2_d)

r2_r=random(X_train,y_train,X_test)
accrf.append(r2_r)

In [28]:
result6=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)
result6

C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:86: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Linear'][idex]=acclin[number]
C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:87: FutureWarning: Chain

Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806

In [36]:
result4=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)
result4

C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:86: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Linear'][idex]=acclin[number]
C:\Users\my pc\AppData\Local\Temp\ipykernel_1256\3062498134.py:87: FutureWarning: Chain

Linear      SVMl     SVMnl  Decision    Random
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806