In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        featurename= fit1.get_support(indices=True)
        selected_features=df2.columns[featurename]
        #Converting index panads to alist
        features=selected_features.to_list() 
        selectk_features = fit1.transform(indep_X)
        return selectk_features,features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
   
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def KPCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,n): 
    
    dataframe=pd.DataFrame(index=[n],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [2]:
dataset = pd.read_csv('Wine.csv')
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [3]:
indep_X=dataset.iloc[:, 0:13]
dep_Y= dataset.iloc[:, 13]

In [4]:
X_train, X_test, y_train, y_test=split_scalar(indep_X,dep_Y)

In [5]:
X_train

array([[ 0.79996869,  0.63400362,  0.71783316, ...,  0.05445565,
         1.0713277 ,  0.31500451],
       [-0.49875982,  0.06171955, -0.61072701, ..., -0.93473577,
        -1.39249704, -0.18138885],
       [-1.29797736, -1.16332605, -0.24168252, ...,  0.18348062,
         0.75296832,  0.45068536],
       ...,
       [-0.72353975, -0.69834524, -0.64763146, ...,  0.48453887,
         0.51765922, -1.33964004],
       [ 1.12465081, -0.63575167, -0.90596261, ..., -0.16058596,
         1.02980256,  0.77830498],
       [ 1.44933294,  0.10642924,  0.42259757, ..., -1.40782731,
        -1.21255479, -0.29721397]])

In [6]:
def KPCA(X_train,X_test):
    from sklearn.decomposition import KernelPCA as KPCA
    kpca = KPCA(n_components = 5, kernel='rbf')
    X_train = kpca.fit_transform(X_train)
    X_test = kpca.transform(X_test)
    return X_train,X_test

In [7]:
X_train,X_test=KPCA(X_train,X_test)

In [8]:
X_train

array([[ 4.50011250e-01, -1.80116918e-01,  2.94019115e-02,
         2.15467303e-02,  7.64391463e-02],
       [-5.09089209e-01, -1.77082320e-01, -1.40758319e-01,
        -2.15780951e-01, -1.18688297e-01],
       [ 2.29121437e-01,  2.28679883e-01,  1.40496261e-02,
         1.64234546e-01,  2.05009409e-02],
       [-3.90949642e-01, -2.25828417e-01, -2.30942919e-01,
         1.50958826e-01,  2.35166888e-01],
       [ 4.57392527e-01, -3.28756722e-01,  1.97241095e-01,
        -5.73209133e-02,  1.86311304e-01],
       [-4.36756384e-01, -1.22538548e-01, -2.41198866e-01,
         4.04398927e-02,  4.80118786e-01],
       [-5.39673323e-01, -1.97406443e-01, -9.25414127e-02,
        -3.22700779e-01, -2.23208714e-01],
       [ 5.08259507e-01, -1.81476826e-01,  4.08715065e-02,
         9.90201097e-02, -9.38580857e-02],
       [-1.11848596e-01, -1.71841623e-01,  1.52600040e-01,
         3.69293705e-01, -1.41260307e-01],
       [ 5.56068568e-01, -6.70094446e-02, -1.13943932e-01,
        -1.49544051e-01

In [9]:
X_test

array([[ 5.17248546e-01, -2.07333544e-01, -1.52042248e-01,
        -3.30247434e-02,  4.64564899e-02],
       [-3.56597283e-01, -2.70784278e-01, -7.74209860e-02,
         3.69447776e-01,  2.78966926e-01],
       [ 2.02090216e-01,  2.79199332e-01, -5.51545102e-02,
         2.07107190e-01, -1.38186103e-01],
       [ 5.07709650e-01, -2.37430918e-01,  1.11961603e-01,
         6.10495031e-02,  5.62624974e-02],
       [-5.26740396e-02,  9.71106943e-02,  1.25947535e-01,
         1.57809806e-01, -1.89015298e-01],
       [-5.83105174e-03, -1.81217077e-03,  2.02285699e-01,
         2.25211064e-01, -1.93922713e-03],
       [ 4.51103227e-01, -2.52828246e-01,  6.41179448e-02,
        -1.35778778e-01,  1.84181812e-01],
       [-5.25609664e-01, -2.39510890e-01,  1.05744317e-02,
        -8.80608731e-02, -1.69576258e-01],
       [-5.83763877e-02,  5.82529718e-01, -1.73605272e-01,
        -8.47244773e-02, -1.18349191e-01],
       [-2.11363794e-01,  4.50770889e-01,  5.45541760e-03,
        -2.13987985e-01

In [10]:
pd.DataFrame(X_train, columns=['PCA 1','PCA 2','PCA 3','PCA 4','PCA 5'])

PCA 1     PCA 2     PCA 3     PCA 4     PCA 5
0    0.450011 -0.180117  0.029402  0.021547  0.076439
1   -0.509089 -0.177082 -0.140758 -0.215781 -0.118688
2    0.229121  0.228680  0.014050  0.164235  0.020501
3   -0.390950 -0.225828 -0.230943  0.150959  0.235167
4    0.457393 -0.328757  0.197241 -0.057321  0.186311
..        ...       ...       ...       ...       ...
128 -0.100543  0.558139 -0.233071  0.069241 -0.155470
129  0.025584  0.490886 -0.313947  0.044085 -0.143497
130 -0.034820  0.549566  0.027387  0.043661  0.105890
131  0.550044 -0.203264 -0.151068  0.024147 -0.204873
132 -0.446339 -0.359355 -0.062839  0.090991 -0.082757

[133 rows x 5 columns]

In [11]:
Column_names=['PCA 1','PCA 2','PCA 3','PCA 4','PCA 5']
pd.DataFrame(X_test, columns=Column_names)

PCA 1     PCA 2     PCA 3     PCA 4     PCA 5
0   0.517249 -0.207334 -0.152042 -0.033025  0.046456
1  -0.356597 -0.270784 -0.077421  0.369448  0.278967
2   0.202090  0.279199 -0.055155  0.207107 -0.138186
3   0.507710 -0.237431  0.111962  0.061050  0.056262
4  -0.052674  0.097111  0.125948  0.157810 -0.189015
5  -0.005831 -0.001812  0.202286  0.225211 -0.001939
6   0.451103 -0.252828  0.064118 -0.135779  0.184182
7  -0.525610 -0.239511  0.010574 -0.088061 -0.169576
8  -0.058376  0.582530 -0.173605 -0.084724 -0.118349
9  -0.211364  0.450771  0.005455 -0.213988 -0.049040
10 -0.425411 -0.096825 -0.194390 -0.241158  0.131564
11 -0.388885 -0.219897 -0.058611 -0.042422 -0.130462
12  0.551945 -0.383603  0.035752 -0.063842 -0.044571
13  0.264268  0.192268 -0.066688  0.177283 -0.164856
14 -0.411036 -0.307372  0.096290  0.143707  0.176571
15  0.039514  0.542244 -0.184322  0.171338 -0.141146
16  0.286873 -0.187746  0.202739 -0.026149  0.211448
17  0.407874 -0.325906  0.064368 -0.004643 -0.046992
18 -0.271129  0.115974 -0.287511 -0.103065  0.051963
19  0.550317 -0.217410 -0.002771 -0.133993  0.016111
20  0.171464  0.164286 -0.246735  0.218309 -0.264671
21  0.374313  0.032329 -0.068985 -0.261030  0.273090
22  0.240492 -0.033402  0.410184 -0.006363  0.285266
23  0.074217  0.557981 -0.228913 -0.034188 -0.147895
24 -0.160702  0.137676 -0.088852 -0.104341  0.075057
25 -0.036968  0.525885 -0.061668  0.012055 -0.039935
26  0.010366  0.400048  0.143130  0.065846 -0.107173
27 -0.124471  0.521408  0.102566 -0.117322  0.070103
28 -0.150463  0.158664  0.315245 -0.138819  0.125747
29 -0.511467 -0.330368 -0.123701  0.039886 -0.030252
30  0.489448 -0.139209 -0.000661 -0.228820  0.083404
31  0.561047 -0.298297 -0.013973  0.026338 -0.076230
32 -0.273997  0.241552  0.179942 -0.186626 -0.129283
33  0.297445 -0.214366  0.052492 -0.062403  0.034271
34  0.488003 -0.225976 -0.198983 -0.075122 -0.144126
35  0.471112  0.005477 -0.147183  0.065497 -0.136861
36 -0.449297 -0.226061  0.012150 -0.243974  0.109276
37 -0.291401  0.296630  0.018027 -0.275952 -0.073424
38  0.096801  0.416968 -0.052187  0.202630 -0.018797
39 -0.556342 -0.373297  0.032911 -0.007153  0.009624
40  0.415868  0.110446  0.129446 -0.160226  0.126051
41  0.439939 -0.210185  0.209563 -0.042677  0.113362
42  0.088525  0.503003 -0.022947  0.162497 -0.156978
43 -0.084345  0.477822 -0.421504  0.000561 -0.016939
44 -0.071896  0.514623  0.184054 -0.020187  0.064220

In [12]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [14]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [15]:
import warnings
warnings.filterwarnings('ignore')

In [16]:
dataframe=KPCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,5)
dataframe

Logistic SVMl SVMnl  KNN Navie  Decision Random
5      1.0  1.0   1.0  1.0   1.0  0.955556    1.0