In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        featurename= fit1.get_support(indices=True)
        selected_features=df2.columns[featurename]
        #Converting index panads to alist
        features=selected_features.to_list() 
        selectk_features = fit1.transform(indep_X)
        return selectk_features,features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
   
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def LDA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,n): 
    
    dataframe=pd.DataFrame(index=[n],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [2]:
dataset = pd.read_csv('Wine.csv')
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [3]:
indep_X=dataset.iloc[:, 0:13]
dep_Y= dataset.iloc[:, 13]

In [4]:
dep_Y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Customer_Segment, Length: 178, dtype: int64

In [5]:
dataset['Customer_Segment'].value_counts()

Customer_Segment
2    71
1    59
3    48
Name: count, dtype: int64

In [6]:
X_train, X_test, y_train, y_test=split_scalar(indep_X,dep_Y)

In [7]:
X_train

array([[ 0.79996869,  0.63400362,  0.71783316, ...,  0.05445565,
         1.0713277 ,  0.31500451],
       [-0.49875982,  0.06171955, -0.61072701, ..., -0.93473577,
        -1.39249704, -0.18138885],
       [-1.29797736, -1.16332605, -0.24168252, ...,  0.18348062,
         0.75296832,  0.45068536],
       ...,
       [-0.72353975, -0.69834524, -0.64763146, ...,  0.48453887,
         0.51765922, -1.33964004],
       [ 1.12465081, -0.63575167, -0.90596261, ..., -0.16058596,
         1.02980256,  0.77830498],
       [ 1.44933294,  0.10642924,  0.42259757, ..., -1.40782731,
        -1.21255479, -0.29721397]])

Example:
Case 1: 3 Features, 2 Classes
n_features = 3
n_classes = 2
n_components must be:
n_components
≤
min
⁡
(
3
,
2
−
1
)
=
1
n_components≤min(3,2−1)=1
Case 2: 5 Features, 4 Classes
n_features = 5
n_classes = 4
n_components must be:
n_components
≤
min
⁡
(
5
,
4
−
1
)
=
3
n_components≤min(5,4−1)=3


In [8]:
def LDA(X_train,X_test,y_train):
    from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
    lda = LDA(n_components = 2)
    X_train = lda.fit_transform(X_train,y_train)
    X_test = lda.transform(X_test)
    return X_train,X_test

In [9]:
X_train,X_test=LDA(X_train,X_test,y_train)

In [10]:
X_train

array([[ 3.75722986e+00,  1.78224173e+00],
       [-3.71779979e+00,  8.55757484e-01],
       [ 4.41722893e-02, -2.02249034e+00],
       [-3.50295061e+00,  1.99910076e+00],
       [ 3.87566163e+00,  2.65077482e+00],
       [-3.31635950e+00,  7.26729526e-01],
       [-3.76757806e+00,  1.03585429e+00],
       [ 3.50642318e+00,  1.01134789e-01],
       [-5.56617679e+00,  2.31052117e+00],
       [ 5.52600002e+00,  6.92702501e-01],
       [-3.34933278e-01, -3.89801248e+00],
       [-4.83234812e+00,  3.19745682e+00],
       [-3.43511567e+00,  9.59123009e-01],
       [ 1.06452054e+00, -2.32005170e+00],
       [-3.47410738e+00,  6.35730414e-01],
       [-5.06710351e+00,  2.38898005e+00],
       [ 2.95021113e+00,  1.13904083e+00],
       [-1.87126516e+00, -4.32025549e-01],
       [-3.96376090e+00, -1.85802042e-01],
       [ 9.49159879e-01, -3.32074700e+00],
       [-1.84114933e+00, -5.83464878e-01],
       [-3.17380882e+00,  1.49403616e+00],
       [ 4.69174963e-01, -1.18843006e+00],
       [ 4.

In [11]:
X_test

array([[ 3.81260158,  1.42768022],
       [-5.21048071,  1.69416574],
       [ 0.48912124, -3.3931783 ],
       [ 2.11280014,  0.86466433],
       [ 0.18861347, -1.3043133 ],
       [ 4.96821244, -2.33039876],
       [ 4.82442302,  2.9027888 ],
       [-5.50222966,  0.86073107],
       [ 1.1848033 , -2.41061817],
       [-0.64541546, -2.33949018],
       [-2.26869621,  1.72936647],
       [-4.97841089,  1.90056168],
       [ 5.20565649,  3.17078798],
       [ 2.45294044, -2.64942247],
       [-4.24871686,  2.05909187],
       [ 0.5284542 , -4.69082892],
       [ 4.05483725,  1.79532273],
       [ 6.42019493,  3.82383717],
       [-2.42567193, -1.08146037],
       [ 5.04345481,  1.83331459],
       [ 2.32097763, -2.80635325],
       [ 2.40944434,  0.95645842],
       [ 1.75810849,  0.34503493],
       [ 1.37437851, -2.47069367],
       [-1.15314017, -0.96468356],
       [-0.3729784 , -2.8373037 ],
       [ 0.99808675, -2.71329767],
       [-0.97235656, -3.34078227],
       [ 0.93449044,

In [12]:
pd.DataFrame(X_train, columns=['LDA 1','LDA 2'])

LDA 1     LDA 2
0    3.757230  1.782242
1   -3.717800  0.855757
2    0.044172 -2.022490
3   -3.502951  1.999101
4    3.875662  2.650775
..        ...       ...
128 -1.783102 -3.795080
129  0.822863 -2.688207
130  0.111344 -3.652006
131  4.126268  0.727353
132 -4.410718  3.015340

[133 rows x 2 columns]

In [13]:
Column_names=['LDA 1','LDA 2']
pd.DataFrame(X_test, columns=Column_names)

LDA 1     LDA 2
0   3.812602  1.427680
1  -5.210481  1.694166
2   0.489121 -3.393178
3   2.112800  0.864664
4   0.188613 -1.304313
5   4.968212 -2.330399
6   4.824423  2.902789
7  -5.502230  0.860731
8   1.184803 -2.410618
9  -0.645415 -2.339490
10 -2.268696  1.729366
11 -4.978411  1.900562
12  5.205656  3.170788
13  2.452940 -2.649422
14 -4.248717  2.059092
15  0.528454 -4.690829
16  4.054837  1.795323
17  6.420195  3.823837
18 -2.425672 -1.081460
19  5.043455  1.833315
20  2.320978 -2.806353
21  2.409444  0.956458
22  1.758108  0.345035
23  1.374379 -2.470694
24 -1.153140 -0.964684
25 -0.372978 -2.837304
26  0.998087 -2.713298
27 -0.972357 -3.340782
28  0.934490 -0.593791
29 -4.729188  2.046844
30  4.644172  2.135986
31  3.343602  1.383761
32 -1.064662 -1.080313
33  3.221134  2.800218
34  4.220147  1.758182
35  3.084431 -0.473907
36 -3.414740  1.864021
37 -0.972958 -2.006355
38 -0.699012 -3.157372
39 -4.691947  1.952875
40  3.801914 -0.025248
41  3.430227  1.090354
42  0.489553 -3.139830
43 -0.089260 -2.458070
44 -1.201071 -3.387889

In [14]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [15]:
acclog,accsvml

([], [])

In [16]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [17]:
import warnings
warnings.filterwarnings('ignore')

In [18]:
dataframe=LDA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,2)
dataframe

Logistic      SVMl SVMnl       KNN     Navie  Decision    Random
2      1.0  0.977778   1.0  0.977778  0.977778  0.977778  0.977778