In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt



def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=chi2, k=n)
        fit1= test.fit(indep_X,dep_Y)
        featurename= fit1.get_support(indices=True)
        selected_features=df2.columns[featurename]
        #Converting index panads to alist
        features=selected_features.to_list() 
        selectk_features = fit1.transform(indep_X)
        return selectk_features,features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
 
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report 
        #from sklearn.metrics import confusion_matrix
        #cm = confusion_matrix(y_test, y_pred)
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return  classifier,Accuracy,report,X_test,y_test,cm

def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
   
def Navie(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm         
    
    
def knn(X_train,y_train,X_test):
           
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
def Decision(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm      


def random(X_train,y_train,X_test):
        
        # Fitting K-NN to the Training set
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return  classifier,Accuracy,report,X_test,y_test,cm
    
def PCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,n): 
    
    dataframe=pd.DataFrame(index=[n],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [36]:
dataset = pd.read_csv('Wine.csv')
dataset

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [37]:
indep_X=dataset.iloc[:, 0:13]
dep_Y= dataset.iloc[:, 13]

In [38]:
X_train, X_test, y_train, y_test=split_scalar(indep_X,dep_Y)

In [39]:
X_train

array([[ 0.79996869,  0.63400362,  0.71783316, ...,  0.05445565,
         1.0713277 ,  0.31500451],
       [-0.49875982,  0.06171955, -0.61072701, ..., -0.93473577,
        -1.39249704, -0.18138885],
       [-1.29797736, -1.16332605, -0.24168252, ...,  0.18348062,
         0.75296832,  0.45068536],
       ...,
       [-0.72353975, -0.69834524, -0.64763146, ...,  0.48453887,
         0.51765922, -1.33964004],
       [ 1.12465081, -0.63575167, -0.90596261, ..., -0.16058596,
         1.02980256,  0.77830498],
       [ 1.44933294,  0.10642924,  0.42259757, ..., -1.40782731,
        -1.21255479, -0.29721397]])

In [40]:
def PCA(X_train,X_test):
    from sklearn.decomposition import PCA
    pca = PCA(n_components = 5)
    X_train = pca.fit_transform(X_train)
    X_test = pca.transform(X_test)
    explained_variance = pca.explained_variance_ratio_
    return X_train,X_test, explained_variance

In [41]:
X_train,X_test, explained_variance=PCA(X_train,X_test)
explained_variance

array([0.37281068, 0.18739996, 0.10801208, 0.07619859, 0.06261922])

In [42]:
X_train

array([[ 2.12849974e+00, -1.01973208e+00,  8.26209888e-02,
         6.78090471e-01,  4.27091942e-01],
       [-2.94812519e+00, -2.54806705e-01,  1.14589113e+00,
        -5.97968964e-01, -5.18370178e-01],
       [ 1.91979542e+00,  1.33701156e+00, -4.02244683e-01,
         7.07416420e-01,  4.58701327e-02],
       [-2.13337607e+00, -9.45897150e-01,  1.40277015e+00,
         1.39579872e+00,  6.91567767e-01],
       [ 2.23680281e+00, -2.26983910e+00, -8.77499126e-01,
         4.36801265e-01, -9.58293769e-01],
       [-2.28747076e+00, -1.99359253e-01,  7.97227232e-01,
         1.23396178e+00, -3.50435082e-01],
       [-2.97244958e+00, -2.96522642e-01,  9.31504047e-01,
        -1.06705468e+00, -1.98434785e-01],
       [ 2.61809796e+00, -7.76070011e-01,  8.30660247e-02,
         2.24081998e-01,  7.26156222e-01],
       [-1.04705463e+00, -3.49093326e+00, -1.29203589e+00,
        -8.95933972e-01,  5.71604442e-01],
       [ 2.60981596e+00,  7.34569695e-02,  1.78959140e-01,
        -4.93030107e-01

In [43]:
X_test

array([[ 2.21435735, -0.94903218,  0.95228447,  0.78791127, -0.22041183],
       [-2.50659973, -1.8189127 ,  0.45680555,  1.58958192,  0.37747294],
       [ 2.12730524,  1.84889911, -0.06650656, -0.53349371,  0.4309516 ],
       [ 2.50886727, -1.2717395 , -0.51542137,  0.84228632,  0.28537278],
       [-0.37546624,  0.56631262, -0.61477967, -0.89497518,  3.24197341],
       [ 1.36750624, -0.10407461, -5.10950965,  0.49922603,  0.25264942],
       [ 2.13754395, -1.51780749, -0.19823085,  0.44985117, -1.27817566],
       [-3.03876331, -0.67608136,  0.08506826, -0.70573647,  0.82904107],
       [-0.2758078 ,  2.17934109,  0.46001318, -0.79218027,  0.21777133],
       [-1.25059924,  2.13272889,  0.03829563, -0.8410568 , -0.33534478],
       [-2.17229537, -0.26937194,  0.90079853, -0.37203801, -0.85762617],
       [-4.15065395, -0.59248433,  1.29975265, -0.75852251,  0.59615668],
       [ 3.13110267, -2.16664974,  0.51087192, -0.41052281, -0.58379615],
       [ 2.34763044,  1.34053226,  0.1

In [44]:
pd.DataFrame(X_train, columns=['PCA 1','PCA 2','PCA 3','PCA 4','PCA 5'])

PCA 1     PCA 2     PCA 3     PCA 4     PCA 5
0    2.128500 -1.019732  0.082621  0.678090  0.427092
1   -2.948125 -0.254807  1.145891 -0.597969 -0.518370
2    1.919795  1.337012 -0.402245  0.707416  0.045870
3   -2.133376 -0.945897  1.402770  1.395799  0.691568
4    2.236803 -2.269839 -0.877499  0.436801 -0.958294
..        ...       ...       ...       ...       ...
128 -0.540398  2.693526  0.811081 -0.303555  0.565140
129  0.294211  2.430463  1.023450 -0.934138 -0.368802
130 -0.033184  2.066114 -0.563365  0.956918  0.007739
131  2.886899 -0.714086  1.023053 -0.433348  0.698064
132 -2.392796 -2.132222  0.777386 -0.698074 -0.466502

[133 rows x 5 columns]

In [45]:
Column_names=['PCA 1','PCA 2','PCA 3','PCA 4','PCA 5']
pd.DataFrame(X_test, columns=Column_names)

PCA 1     PCA 2     PCA 3     PCA 4     PCA 5
0   2.214357 -0.949032  0.952284  0.787911 -0.220412
1  -2.506600 -1.818913  0.456806  1.589582  0.377473
2   2.127305  1.848899 -0.066507 -0.533494  0.430952
3   2.508867 -1.271740 -0.515421  0.842286  0.285373
4  -0.375466  0.566313 -0.614780 -0.894975  3.241973
5   1.367506 -0.104075 -5.109510  0.499226  0.252649
6   2.137544 -1.517807 -0.198231  0.449851 -1.278176
7  -3.038763 -0.676081  0.085068 -0.705736  0.829041
8  -0.275808  2.179341  0.460013 -0.792180  0.217771
9  -1.250599  2.132729  0.038296 -0.841057 -0.335345
10 -2.172295 -0.269372  0.900799 -0.372038 -0.857626
11 -4.150654 -0.592484  1.299753 -0.758523  0.596157
12  3.131103 -2.166650  0.510872 -0.410523 -0.583796
13  2.347630  1.340532  0.193754 -0.708190  0.664149
14 -2.125075 -1.904488 -0.746128  0.565280 -0.570506
15  0.855563  3.377716  0.357890 -0.385004 -0.390926
16  1.981673 -1.505112 -1.116345  0.641486 -1.950769
17  3.637419 -2.573651  0.369835 -0.775216 -1.180185
18 -1.711865  0.916403  1.670181 -0.135181 -1.163727
19  2.916441 -0.796804 -0.180380 -0.647029 -0.632678
20  2.324917  1.725720  1.864520 -1.465882  1.120564
21  1.223963 -0.092180 -0.008942 -0.105456 -1.148936
22  1.054057 -0.777610 -2.022011  0.581485 -0.269420
23  0.497947  2.111859  0.444554 -0.674158  0.169313
24 -1.398811  1.472150  0.939821 -0.299543 -2.424779
25 -0.170187  1.943921 -0.110152 -0.231451  0.586005
26  0.125020  1.241291 -0.696311 -0.814315  0.937073
27 -0.704322  2.312205 -0.711083 -0.091859 -0.883737
28 -1.218171  0.897914 -1.898380 -0.092397 -1.364333
29 -2.859208 -1.449558  0.917387 -0.435718 -0.435778
30  1.873027 -0.739923 -0.060053 -1.048601 -0.710219
31  2.786936 -1.430738  0.519883  0.305080  0.197923
32 -1.673710  1.167551 -0.810677 -0.924934  1.211213
33  1.229584 -1.746820 -0.152520 -0.203348  0.353241
34  2.593631 -1.028640  1.519666 -0.982607 -0.298492
35  2.168401  0.071694  0.647182  0.090491  0.836010
36 -2.143659 -1.042234  0.057230  0.105362 -1.120536
37 -1.823836  1.582401  0.070056 -1.062792 -0.545288
38  1.030581  2.264229 -0.106980  0.545274  0.366326
39 -2.516776 -1.626007 -0.209434  0.230784  0.296320
40  1.829825  0.320524 -1.020871 -0.520252 -0.593558
41  2.572717 -1.256477 -1.469102 -0.332881 -0.704058
42  0.805362  2.290937 -0.189827 -0.287616  1.216849
43 -0.442631  2.355620  1.511267  0.057902 -0.343429
44 -0.363284  2.317442 -0.981141 -0.207684 -0.781673

In [46]:
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

In [47]:
acclog,accsvml

([], [])

In [48]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [49]:
import warnings
warnings.filterwarnings('ignore')

In [50]:
dataframe=PCA_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf,5)
dataframe

Logistic      SVMl SVMnl  KNN Navie  Decision    Random
5  0.977778  0.955556   1.0  1.0   1.0  0.977778  0.977778